#!/bin/bash 
LOG=/tmp/lin.txt
echo "--------------my_compiler---------------------" >> $LOG
echo "$(date)" >> $LOG
echo "$(pwd)" >> $LOG
echo "$0" "$@" >> $LOG

array=$@
array2=()
objs=()
output=""
output_flag=0
shared=0
# array2+=("-static")
compiler=""

case "$0" in
*/gcc)
	compiler="/usr/bin/gcc"
;;
*/g++)
	compiler="/usr/bin/g++"
;;
*/cc)
	compiler="/usr/bin/cc"
;;
*)
	echo "unkonw $0" >>$LOG
	exit 1
esac


for element in ${array[@]}
do
	#echo $element >>$LOG
	if [[ "$element" != "-shared" ]]; then
		array2+=($element)
		#echo $element >>$LOG
	else
		shared=1
	fi
	case "$element" in
		*.o)
		objs+=($element)
		#echo $element >>$LOG
		;;
	esac
	if [[ "$element" == "-o" ]]; then
		output_flag=1
		continue
	fi
	if [[ "$output_flag" == 1 ]]; then
		output_flag=0
		output=$element
		case "$element" in
			*.o)
			;;
			*)
				array2+=("-static")
				# array2+=("-static-pie")
				# array2+=("-fpie")
				# array2+=("-fPIE")
			#	array2+=("-static-libgcc")
			#	array2+=("-static-libasan")
			#	array2+=("-static-libtsan")
			#	array2+=("-static-liblsan")
			#	array2+=("-static-libubsan")
			;;
		esac
	fi
done

echo "-o" "${output}" >> $LOG
echo "objs" "${objs[@]}" >> $LOG
cmd_my=""
if [[ $shared == 1 ]]; then
	cmd_my="/usr/bin/ar rcs"
	cmd_my+=" $output"
	cmd_my+=" ${objs[@]}" 
else
	cmd_my="$compiler ${array2[@]}" 
fi
echo "$cmd_my" >> $LOG
$cmd_my 
ans=$?
cmd_org="$compiler $@"
echo "diff command" >>$LOG
diff  <(echo "$cmd_my" ) <(echo "$cmd_org") >>$LOG
#$compiler "$@"
#ans=$?

#if [[ "$output" != ""  ]]; then
#	file "$output" >>$LOG
#fi
echo "-----------------------------------------" >>$LOG
exit $ans
