#!/bin/bash
LOG=/u/lisimon/tmp/lin.txt
echo "--------------my_compiler---------------------" >> $LOG
echo "$(date)" >> $LOG
echo "$(pwd)" >> $LOG
echo "$0" "$@" >> $LOG
# echo "STATIC_GET_HOME $STATIC_GET_HOME"
export MUSL_HOME="$STATIC_GET_HOME/musl"
# export MUSL_HOME="/u/lisimon/workhome/code/x86_64-linux-musl-cross/x86_64-linux-musl"
# REAL_GCC_PATH=/remote/vcs_source02/lisimon/code/x86_64-linux-musl-cross/
# REAL_GCC_PATH="/u/lisimon/script/subOS.sh /usr"
REAL_GCC_PATH=" /depot/gcc-13.2.0"


array=$@
array2=()
objs=()
output=""
output_flag=0
shared=0
# array2+=("-static")
# array2+=("-I$MUSL_HOME/include")
# array2+=("-L$MUSL_HOME/lib")
# array2+=("-lc")
# array2+=("-lm")
# array2+=("-lrt")
# array2+=("-nostdinc")
# array2+=("-nostdinc++")
# array2+=("-nostdlib")
# array2+=("-nostdlib++")
# array2+=("-nostartfiles")
# array2+=("-L$REAL_GCC_PATH/lib64")

compiler=""


case "$0" in
    */gcc)
        compiler="$REAL_GCC_PATH/bin/gcc"
        array2+=("-specs")
        array2+=("$MUSL_HOME/lib/musl-gcc.specs")
    ;;
    */g++)
        compiler="$REAL_GCC_PATH/bin/g++"
        # array2+=("-I$MUSL_HOME/include")
        # array2+=("-L$MUSL_HOME/lib")
        # array2+=("-lc")
        # array2+=("-lm")
        # array2+=("-lrt")
		array2+=("-specs")
        array2+=("$MUSL_HOME/lib/musl-gcc_my.specs")
        # array2+=("-nostdlib")
        
    ;;
    */cc)
        compiler="$REAL_GCC_PATH/bin/gcc"
        array2+=("-specs")
        array2+=("$MUSL_HOME/lib/musl-gcc.specs")
        
    ;;
    *)
        echo "unkonw $0" >>$LOG
        exit 1
esac


for element in ${array[@]}
do
    #echo $element >>$LOG
    if [[ "$element" != "-shared" ]]; then
        array2+=($element)
        #echo $element >>$LOG
    else
        shared=1
    fi
    case "$element" in
        *.o)
            objs+=($element)
            #echo $element >>$LOG
        ;;
    esac
    if [[ "$element" == "-o" ]]; then
        output_flag=1
        continue
    fi
    if [[ "$output_flag" == 1 ]]; then
        output_flag=0
        output=$element
        case "$element" in
            *.o)
            ;;
            *)
                array2+=("-static")
                
                # array2+=("-static-pie")
                # array2+=("-fpie")
                # array2+=("-fPIE")
                #	array2+=("-static-libgcc")
                #	array2+=("-static-libasan")
                #	array2+=("-static-libtsan")
                #	array2+=("-static-liblsan")
                #	array2+=("-static-libubsan")
            ;;
        esac
    fi
done


echo "-o" "${output}" >> $LOG
echo "objs" "${objs[@]}" >> $LOG
cmd_my=""
if [[ $shared == 1 ]]; then
    cmd_my="$REAL_GCC_PATH/bin/ar rcs"
    cmd_my+=" $output"
    cmd_my+=" ${objs[@]}"
else
    cmd_my="$compiler ${array2[@]}"
fi
echo "$cmd_my" >> $LOG
$cmd_my
ans=$?
cmd_org="$compiler $@"
echo "diff command" >>$LOG
diff  <(echo "$cmd_my" ) <(echo "$cmd_org") >> $LOG
#$compiler "$@"
#ans=$?
#if [[ "$output" != ""  ]]; then
#	file "$output" >>$LOG
#fi
echo "-----------------------------------------" >>$LOG
exit $ans
